language: node_js
node_js:
  - "stable"
install:
  - "npm install"
cache:
  directories:
  - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database propertyprolite;' -U postgres    
script:
  - "npm run test"
after_success: 
  - npm run coverage
branches:
  only:
    - develop
notifications:
  email: false